name: Hardcore
main: com.psychobit.hardcore.Hardcore
version: 3.0
commands:
  hardcore:
    description: Lookup player survival time.
    usage: /hardcore slay|res|info
  hcsmp:
    description: Lookup player survival time.
    usage: /hardcore slay|res|info